### ISSUE TITLE
Add icon for webpage tab

### ISSUE THREAD

**Issue by Rehaan99** [Rehaan99/RTSWW2#10]
Add a small icon that will show on the tab.

**Comment by Ajoy10** [comment]
Can I create a basic icon and add it?

**Comment by Rehaan99** [comment]
Sure.

**Comment by Ajoy10** [comment]
Shouldn't it be PvZ rather than PvS. Should I use PvS anyways?

**Comment by Rehaan99** [comment]
Oh yeah, you're right. I'll change that.
