### ISSUE TITLE
Resource increase pop up is in the wrong place

### ISSUE THREAD

**Issue by Rehaan99** [Rehaan99/RTSWW2#33]
After moving the positioning of the Resource text on the top bar due to adding more defender cards the pop up message showing points being added is now in the wrong position, move it more to the right (increase x coordinate).

**Comment by denquinlan** [comment]
I’d like to take a crack at this

**Comment by Rehaan99** [comment]
Sure thing!

**Comment by Rehaan99** [comment]
Doesn't seem like denquinlan is going to do this, if anyone else would like to have a go instead. (It should be a very easy one!)
