### ISSUE TITLE
Change defender health colour based on % left

### ISSUE THREAD

**Issue by Rehaan99** [Rehaan99/RTSWW2#41]
Currently defenders have their health showing above their heads in green, we want to change this so that it starts off as a dark green and progresses to yellow and then red. (e.g green = 70%-100% health, yellow = 40%-70%, red = under 40%) though percentages and colours can be tweaked if better colours/values are found.

**Comment by lewisyng** [comment]
Hey, I'd like to do this issue. Just to be clear, as far as I can see there is no health bar at all at the moment. Just the health counter in red

**Comment by Rehaan99** [comment]
Yep! Feel free to pick it up. I was thinking just keeping the health counter and changing it's colour. However, if you'd like to implement a health bar instead you can do.

**Comment by lewisyng** [comment]
Just added a healthbar that changes color in 20 increments

**Comment by Rehaan99** [comment]
@lewisyng would you like to make the same change you made on the enemies to the defenders also?

**Comment by lewisyng** [comment]
@Rehaan99 i just added a healthbar to the defenders

**Comment by Rehaan99** [comment]
There were some bugs in #47, fixed in #48 .
